Caleydo/lineupjs

demo/lineup_demo.js
=> Address gist loading issue described in #155

src/lineup.ts, src/provider/ADataProvider.ts, src/provider/LocalDataProvider.ts, src/provider/RemoteDataProvider.ts, src/ui/ABodyRenderer.ts, src/ui_dialogs.ts, src/utils.ts
extension of feature_146_react
=> Feature 144 jump to search

src/model/CategoricalNumberColumn.ts, src/model/Column.ts, src/model/CompositeNumberColumn.ts, src/model/MultiLevelCompositeColumn.ts, src/model/NumberColumn.ts, src/model/StackColumn.ts, src/renderer.ts
extension of feature_146_react
=> Feature 163 switchable renderer

src/model/AnnotateColumn.ts, src/model/BooleanColumn.ts, src/model/CategoricalColumn.ts, src/model/CategoricalNumberColumn.ts, src/model/Column.ts, src/model/CompositeColumn.ts, src/model/CompositeNumberColumn.ts, src/model/LinkColumn.ts, src/model/MaxColumn.ts, src/model/MeanColumn.ts, src/model/MinColumn.ts, src/model/NestedColumn.ts, src/model/NumberColumn.ts, src/model/Ranking.ts, src/model/ScriptColumn.ts, src/model/SelectionColumn.ts, src/model/StackColumn.ts, src/model/StringColumn.ts, src/model/ValueColumn.ts, src/model/index.ts, src/provider/ACommonDataProvider.ts, src/provider/ADataProvider.ts, src/provider/LocalDataProvider.ts, src/provider/RemoteDataProvider.ts, src/renderer.ts, src/ui/HeaderRenderer.ts, src/utils.ts
=> Feature 165 no data manipulation

src/renderer.ts, src/ui/CanvasBodyRenderer.ts, src/utils.ts
=> Feature 181 clip text improvements

demo/test.html, src/model/Column.ts, src/model/CompositeNumberColumn.ts, src/model/NumberColumn.ts, src/model/StackColumn.ts, src/model/ValueColumn.ts, src/renderer.ts, src/styles/_body_html.scss, src/styles/_body_svg.scss, src/utils.ts
=> Feature lazy column

demo/test.html, src/model/AnnotateColumn.ts, src/model/BooleanColumn.ts, src/model/CategoricalColumn.ts, src/model/CategoricalNumberColumn.ts, src/model/Column.ts, src/model/CompositeColumn.ts, src/model/CompositeNumberColumn.ts, src/model/DummyColumn.ts, src/model/LinkColumn.ts, src/model/MultiLevelCompositeColumn.ts, src/model/NumberColumn.ts, src/model/RankColumn.ts, src/model/ScriptColumn.ts, src/model/SelectionColumn.ts, src/model/StackColumn.ts, src/model/StringColumn.ts, src/model/ValueColumn.ts, src/model/index.ts, src/renderer.ts, src/styles/_body_html.scss, src/styles/_body_svg.scss, src/utils.ts
extension of pull request #205 
related issues:
=> Typed descriptions

src/dialogs/CategoricalFilterDialog.ts, src/dialogs/CategoricalMappingFilterDialog.ts, src/model/CategoricalColumn.ts, src/model/CategoricalNumberColumn.ts
=> Feature missing categorical

src/model/Ranking.ts, src/provider/ACommonDataProvider.ts, src/provider/LocalDataProvider.ts, src/ui/HeaderRenderer.ts
see #241
configurable `maxNestedSortingCriteria` as part of the data provider to specify a hierarchical sorting based on the order of selection criteria. 
i.e. 
1. sort by column A
1. sort by column B -> ties will be sorted by column A if maxNestedSortingCriteria > 1
=> Nested sorting

src/model/CategoricalColumn.ts
=> more conservative restore

demo/lazy_loaded_test.html, src/model/ValueColumn.ts
=> fix not cloned loading state. closes #283 Caleydo/targid_boehringer#575

src/provider/ADataProvider.ts
=> fix #300 option to include description in export

src/config.ts, src/dialogs/ChangeRendererDialog.ts, src/model/CategoricalColumn.ts, src/model/NumberColumn.ts, src/model/StackColumn.ts, src/styles/_vars.scss, src/styles/engine/_header.scss, src/styles/engine/_index.scss, src/styles/header/_summary.scss, src/styles/header/_toolbar.scss, src/styles/renderer/_bar.scss, src/styles/renderer/_categorical.scss, src/styles/renderer/_missing_darker.scss, src/styles/sidePanel/_entry.scss
This PR addresses the changes from https://github.com/sgratzl/taggle2/issues/83#issuecomment-329413172 that can't be done in Taggle2 (and has to be done here).
=> Taggle style improvements

src/styles/engine/_row.scss
See https://github.com/sgratzl/taggle2/issues/104
=> Add padding

src/styles/_vars.scss, src/styles/engine/_row.scss
See Caleydo/lineupjs#325
Related PRs: 
https://github.com/sgratzl/lineupengine/pull/7
https://github.com/sgratzl/taggle2/pull/116
=> Remove `zebra` and add margin bet. rows instead + update row hover

src/model/StringColumn.ts
=> fix #350 string caseinsensitive sorting

src/model/AggregateGroupColumn.ts, src/model/Column.ts, src/model/CompositeColumn.ts, src/model/NumberColumn.ts, src/model/Ranking.ts, src/model/SelectionColumn.ts, src/model/StackColumn.ts, src/renderer/CategoricalCellRenderer.ts, src/renderer/HeatmapCellRenderer.ts, src/renderer/MultiLevelCellRenderer.ts, src/renderer/missing.ts, src/styles/header/_index.scss, src/styles/header/_toolbar.scss, src/styles/old/_header.scss, src/styles/sidePanel/_entry.scss, src/ui/ABodyRenderer.ts, src/ui/CanvasBodyRenderer.ts, src/ui/DOMBodyRenderer.ts, src/ui/HeaderRenderer.ts, src/ui/engine/MultiLevelRenderColumn.ts, src/ui/engine/RenderColumn.ts, src/ui/engine/header.ts
fix #356 get rid of collapse feature
fix #329 stratify by selection
=> fix #356 get rid of collapse feature

package.json, src/dialogs/ADialog.ts, src/dialogs/MappingsFilterDialog.ts, src/styles/_dialogs.scss, src/styles/header/_index.scss, src/styles/header/_toolbar.scss, src/ui/engine/header.ts
Related issue #340.
New dependencies: [popper.js](https://popper.js.org)
Merges into header-redesign branch.
=> Improved popup position

src/dialogs/CategoricalFilterDialog.ts, src/mappingeditor.ts, src/model/CategoricalColumn.ts, src/ui/HeaderRenderer.ts
* avoid dropping on oneself
* better guess the mapping type
* fix detection of empty categorical filter
=> Small fixes

src/model/BoxPlotColumn.ts, src/model/CategoricalColumn.ts, src/model/NumberColumn.ts, src/model/NumbersColumn.ts, src/model/StackColumn.ts, src/styles/renderer/_rank.scss
Closes #401 
**Categorical**
**Numerical**
**Matrix**
=> Rename and cleanup available column visualizations

src/renderer/AggregateGroupRenderer.ts, src/styles/_vars.scss, src/styles/header/_summary.scss, src/styles/renderer/_aggregate.scss, src/styles/renderer/_rank.scss
=> Square bracket for group aggregation 

src/provider/ACommonDataProvider.ts
=> try to resolve description given by object to current ones

src/dialogs/StratifyThresholdDialog.ts, src/model/Column.ts, src/model/Ranking.ts
=> fix #420 unify stratify logic

src/styles/engine/_header.scss, src/styles/header/_summary.scss
Related PR: https://github.com/Caleydo/lineup/pull/19
Closes Caleydo/lineupjs#342
=> Add an axis to the header for numerical columns

src/dialogs/StringFilterDialog.ts, src/styles/_vars.scss, src/styles/header/_summary.scss, src/styles/sidePanel/_search.scss
Closes #424
Closes #425
Improved styling of all form elements in the side panel
=> Improve styling of form elements 

src/styles/header/_toolbar.scss, src/ui/engine/header.ts
=> Add priority indicator to sort and stratify icon

src/styles/taggle/_lod.scss
=> Fix position and visibility of the aggregation arrow in overview mode

src/renderer/DefaultCellRenderer.ts, src/styles/_vars.scss, src/styles/renderer/_categorical.scss, src/styles/renderer/_string.scss
=> Add examples to string renderer of aggregated group

src/renderer/CategoricalStackedDistributionlRenderer.ts, src/styles/renderer/_catdistributionbar.scss, src/utils.ts
Closes Caleydo/lineupjs#487
Closes Caleydo/lineupjs#489
=> Improve categorical renderer style

src/styles/header/_toolbar.scss
Closes https://github.com/Caleydo/tdp_bi_bioinfodb/issues/788
=> hides the header toolbar when taggle is in context mode

src/dialogs/CategoricalFilterDialog.ts
=> #513 uncheck select all if all entries are unchecked
